### ISSUE TITLE
Descriptions of Dataverse installations missing from map

### ISSUE THREAD

**Issue by pdurbin** [IQSS/miniverse#52]
The old map had descriptions of Dataverse installations. @raprasad mentioned that we intend the new map to have these as well.

**Comment by jggautier** [comment]
Descriptions should be there now. You mean this these, right?:

![screen shot 2017-08-30 at 9 28 38 am](https://user-images.githubusercontent.com/18374574/29874767-c8398de4-8d65-11e7-9adb-6e5851ac999a.png)

**Comment by pdurbin** [comment]
Yes! They must have been added since I opened this issue. Thanks! Closing.
