### ISSUE TITLE
Are dataverse category and dataset subject self-reported?

### ISSUE THREAD

**Issue by joehand** [IQSS/miniverse#54]
Do the people that institutions and people that create dataverses or datasets report the dataverse category and dataset subjects?

Thanks!

**Comment by pdurbin** [comment]
@raprasad and others, please see https://botbot.me/freenode/dat/msg/75630499/ and below for more context.

**Comment by jggautier** [comment]
Hey @joehand. Apologies for answering this so late after your post. I haven't been monitoring as much as I should.

TLDR: Yes, the people creating dataverses and datasets choose their own dataverse categories and dataset subjects.

Just more info.: The metrics app is tracking data from just the Harvard Dataverse, which is a "self-curation" installation of Dataverse, so anyone can create dataverses and datasets and describe them with any of the dataverse "categories" and dataset "subjects" from two controlled lists in the software. Hope that helps!

**Comment by jggautier** [comment]
Closing. I think the question was answered.
