### ISSUE TITLE
Metrics bar graph is Y-axis truncated

### ISSUE THREAD

**Issue by xmacex** [IQSS/miniverse#59]
Encouraged by @pdurbin [on Twitter](https://twitter.com/philipdurbin/status/867361245212676096), I'm reporting an issue I noticed on the dataverse.org page http://dataverse.org/metrics, namely that Y-axis is truncated for bar graphs. This violates a rather widely accepted principle of data visualization; in a bargraph with truncated y-axis, the data-to-ink ratio does not remain constant (https://en.wikipedia.org/wiki/Misleading_graph#Truncated_graph, http://callingbullshit.org/tools/tools_misleading_axes.html, http://callingbullshit.org/tools/tools_proportional_ink.html, https://infoactive.co/data-design/ch18.html etc). This is misleading.

![screen shot 2017-05-24 at 16 47 31](https://cloud.githubusercontent.com/assets/879300/26409806/e862e446-40a1-11e7-8a1e-2fb3be442475.png)

The truncation at 1500 leads to visual `d3.max(dataverse_counts_by_month, d => d.running_total - 1500) / d3.min(dataverse_counts_by_month, d => d.running_total - 1500) * 100 - 100` = 159% increase in bar heights (read: _installed Dataverses within the measured period of time_), whereas the non-truncated graph gives `d3.max(dataverse_counts_by_month, d => d.running_total) / d3.min(dataverse_counts_by_month, d => d.running_total) * 100 - 100` = 23% increase. This just in one, vertical dimension, neverminding the two-dimensional area of the bargraphs. A linear regression analysis of the heights or areas of the bars would provide a further line of critique.

If one opens the URL https://services.dataverse.harvard.edu/miniverse/metrics/basic-viz/last12-dataverse-org?iframe=true, changes the `get_metrics_viz_range` range function to return a full y-range [0, y_range_end] like so:

```javascript
function get_metrics_viz_range(metric_array, mod_num){
  var fig_y_min = metric_array[0].running_total;
  var fig_y_max = metric_array[metric_array.length-1].running_total;

  if (fig_y_min < mod_num){
    return [0, fig_y_max + 10];
  }

  var y_range_start = fig_y_min - (fig_y_min % mod_num);
  var y_range_end = fig_y_max - (fig_y_max % mod_num) + mod_num;

  // return [y_range_start, y_range_end];
  return [0, y_range_end];
}
```

and redraws the graph, then the same data looks like this
![screen shot 2017-05-24 at 16 47 21](https://cloud.githubusercontent.com/assets/879300/26409755/c11570fc-40a1-11e7-88fa-7ce728984f22.png).

On [the metrics page](http://dataverse.org/metrics), the same y-axis truncation is done to all the four bargraphs. I would like to propose not truncating the y-axis.

An alternative solution is to change from bar graph to a line graph, which is a chart type in which data-to-ink ratio remains constant.

I apologize I am not sure what would be the best way to provide an issue report for this particular project, I hope this is helpful :) (and really I apologize if I sound like some sort of bargraph troll from the Interwebs, which I'm not, I just stumbled upon this minor issue while considering suggesting adoption of Dataverse at our University)

**Comment by xmacex** [comment]
Just to expand on the second suggestion, here is the same data as a line graph `d3plus.viz().type("line")`, with truncation (ie. original `get_metrics_viz_range`)
![screen shot 2017-05-24 at 17 41 11](https://cloud.githubusercontent.com/assets/879300/26412235/56dd5d9c-40a8-11e7-9c75-1318882fab30.png)

and without truncation (ie. range from 0)

![screen shot 2017-05-24 at 17 41 22](https://cloud.githubusercontent.com/assets/879300/26412254/650ebbfe-40a8-11e7-8cac-e840fe5a74ad.png)

**Comment by pdurbin** [comment]
> and really I apologize if I sound like some sort of bargraph troll from the Interwebs, which I'm not, I just stumbled upon this minor issue while considering suggesting adoption of Dataverse at our University

@xmacex even if you don't like our bar graphs, we'd love for you to adopt Dataverse. 😄 

Thank you very much for all the time and thought you've put into this. I think you're onto something, but I'm glad we aren't quite as bad as this example from the Wikipedia article you linked to:

![screen shot 2017-05-24 at 9 29 20 pm](https://cloud.githubusercontent.com/assets/21006/26432329/fe51ae1e-40c8-11e7-9d29-5ab5fb19391f.png)

The proportional ink article is interesting and I'm still laughing about the graph about the top 10 most read books in the world. 😄 

Please don't hate us if we don't address this issue right away. Here's what we're really working on: http://dataverse.org/goals-roadmap-and-releases

Thanks again!

**Comment by jggautier** [comment]
Looks like [CIMMYT](https://data.cimmyt.org/dataverse/root?q=&types=dataverses&sort=dateSort&order=asc&page=1) Research Data & Software Repository Network fixed this in [their miniverse](https://metrics-data.cimmyt.org/miniverse/metrics/basic-viz/last12).

![screen shot 2017-12-22 at 12 25 21 pm](https://user-images.githubusercontent.com/18374574/34306834-3ae3969e-e713-11e7-9779-bf7f0acff27b.png)

**Comment by pdurbin** [comment]
@jggautier thanks, that's awesome that there are now two public installations of Miniverse. I just added a new "Miniverse URL" column to our internal "known installations" spreadsheet and we should probably consider adding it to the JSON output at https://services.dataverse.harvard.edu/miniverse/map/installations-json

**Comment by pdurbin** [comment]
Now that I'm working on https://github.com/IQSS/metrics.dataverse.org/issues/4 I'm in a much better position to attempt to fix this bug.

**Comment by pdurbin** [comment]
@xmacex if you're interested, I just commented on a potential fix with some screenshots at https://github.com/IQSS/metrics.dataverse.org/issues/4#issuecomment-472137707

In honor of the hashtag you used, I renamed the method to `yAxisTruncation` and played around with it but ultimately commented it out. So there's no truncation in my pull request right now. Thanks again for opening this issue and thanks for your patience.

**Comment by pdurbin** [comment]
I'm going to close this now that https://github.com/IQSS/dataverse-metrics/pull/5 is in QA and has a fix to no avoid Y axis truncation.

For anyone who's interested, there's some discussion at https://github.com/IQSS/dataverse-metrics/issues/4#issuecomment-475304139
