### ISSUE TITLE
Make metrics above installation map on dataverse.org not misleading

### ISSUE THREAD

**Issue by jggautier** [IQSS/miniverse#65]
The count of dataverses, datasets and file downloads above the Dataverse installation map look like they're from all installations, but they're from Harvard Dataverse only. We have no automated way to update those metrics with counts from the known installations.

<img width="982" alt="screen shot 2017-11-28 at 6 04 14 pm" src="https://user-images.githubusercontent.com/18374574/33349057-93c0a94c-d466-11e7-977b-a66b19c78d79.png">

How can we make those numbers not misleading?

(Sorry for the weirdly-phrased titled. Trying not to use it to prescribe a solution.)

**Comment by jggautier** [comment]
Can we remove those numbers (and just have the count of installations in the center)?

**Comment by pdurbin** [comment]
> Can we remove those numbers (and just have the count of installations in the center)?

@jggautier I love this idea.

**Comment by pdurbin** [comment]
The numbers **are** misleading. Check out this tweet from Jochen Apel at https://twitter.com/Duhem_/status/935133423877976065

"Quick, why does this website https://dataverse.org/  say that there are~50k datasets over all installations if Harvard Dataverse alone lists ~75k datasets?"

**Comment by pdurbin** [comment]
See this post for some confusion over the gray dots: https://groups.google.com/d/msg/dataverse-community/eQlSLFgzQXI/t6FANVynBgAJ

**Comment by pdurbin** [comment]
I just approved pull request #66. The change makes sense. @mallove simply commented out the inaccurate metrics. Thanks!

**Comment by pdurbin** [comment]
This looks so much better:

![screen shot 2018-01-23 at 12 34 05 pm](https://user-images.githubusercontent.com/21006/35290949-cb3604f4-0039-11e8-9ac5-4801668358cf.png)

Thank you, @mallove !!

@jggautier you opened this issue. Are you ready to close it?

**Comment by jggautier** [comment]
Closing! Thanks @mallove!

**Comment by pdurbin** [comment]
It was noticed during SpinachCon 2018 ( https://github.com/IQSS/dataverse/issues/4505 ) that the misleading numbers are back so I'm re-opening this issue. Here's a screenshot from today:

![screen shot 2018-04-18 at 4 22 27 pm](https://user-images.githubusercontent.com/21006/38956031-68f9e476-4324-11e8-8cdb-07b3d772ef1c.png)

**Comment by pdurbin** [comment]
I spoke with @djbrooke today about this and he said I could go ahead and create an issue in the main issue tracker so I just did: https://github.com/IQSS/dataverse/issues/5429

Closing this one in favor of the new one.
