### ISSUE TITLE
Titles of bar charts on https://dataverse.org/metrics are misleading

### ISSUE THREAD

**Issue by jggautier** [IQSS/miniverse#67]
@thegaryking noticed that the titles of the bar charts on https://dataverse.org/metrics, Dataverses/Datasets/Files "Added Over Time", are misleading. The metrics in the charts are cumulative, but the titles make it seem as though each bar is counting the number of objects added each month.

<kbd>![screen shot 2018-02-26 at 11 06 18 am](https://user-images.githubusercontent.com/18374574/36680908-1b0a53e8-1ae5-11e8-930b-8c4ff5acbf98.png)</kbd>
_Without hovering over or reading the text on the bar for Feb 2018, it looks like over 50k datasets were added that month, when 181 were added, bringing the total number of datasets to over 50k._

**Comment by jggautier** [comment]
Would the easiest fix be editing the titles to something like **Total number of dataverses/datasets/files over time** (or **over last 12 months**) or **Cumulative count of dataverses/datasets/files...**?

**Comment by pdurbin** [comment]
#59 is related.

**Comment by pdurbin** [comment]
@jggautier I'm working on https://github.com/IQSS/metrics.dataverse.org/issues/4 . Do you still want the wording to be "cumulative count"?

**Comment by jggautier** [comment]
Yes, I think the chart titles could still mislead people.

Maybe another option for the chart titles: "Running total of dataverses/datasets/files added over time".

**Comment by pdurbin** [comment]
@jggautier I like your idea but in practice it's a little long so I tried "Total Dataverses", for example, in my pull request. You can see some screenshots at https://github.com/IQSS/metrics.dataverse.org/issues/4#issuecomment-472137707

**Comment by jggautier** [comment]
I saw. Thanks for the update. That seems clear enough to me, or I might be too close to the problem to tell! But seems easy to test and easy to change if needed.

**Comment by pdurbin** [comment]
Yes, super easy to change. We can just search for the strings in the pull request and change them to whatever we decide is best.

**Comment by pdurbin** [comment]
Now that https://github.com/IQSS/dataverse-metrics/pull/5 is in QA I'm going to close this issue. The decision was use "Total Dataverses", "Total Datasets", etc.
